### PR TITLE
merge

### PR DESCRIPTION
**Pull request by DaviesAguirreBlas**

### CODE REVIEW

**Comment by DaviesAguirreBlas** [comment]
@DaviesAguirreBlas 
@Mariel-ux 
@azanedov 
@lquequejana

**Comment by lquequejana** [comment]
@DaviesAguirreBlas please check my commits

**Review by Mariel-ux — APPROVED** [review]

**Comment by azanedov** [comment]
vanessa.azanedo@gmail.com

**Comment by Mariel-ux** [comment]
@DaviesAguirreBlas 
@azanedov 
@lquequejana 

please add the email next to your name

**Pull request merged**
